annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-18.0.0-b293b98f2e07fd40c43fcacccf19621828d9c9c5.tgz
dateCreated: '2025-12-10T17:59:02.338303Z'
digest: d4bea44714b98dcc10056ecd845670e9031614ae5f855e514457a392150ce8c6
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
restrictions:
  clusterSingleton: true
