annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.0-cd11513174eb20314e31940fad3960ea629c258b.tgz
dateCreated: '2025-12-17T18:13:31.033270Z'
digest: a71540365aff85e11406088d49b490dc4e2fa37165ac852da633c311fec0d497
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
