annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.1-8a9dbc58e61dd99cda751286ecb8e1fd9fe36212.tgz
dateCreated: '2026-01-05T16:15:10.557592Z'
digest: 2ad44528a3ffcfe50e55fc17615d9842456acf4b33f643799636c0810c557ae9
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
