annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-1fa5bd369b4dd0b867765a245636150f516c3a20.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-1fa5bd369b4dd0b867765a245636150f516c3a20.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-1fa5bd369b4dd0b867765a245636150f516c3a20.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-1fa5bd369b4dd0b867765a245636150f516c3a20.tgz
dateCreated: '2025-11-06T07:27:57.595145Z'
digest: 09271e180f1fc5fe5624c1fba39ab3e29d47723b5f84be7ffde42ceb2c317560
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
