annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-0ee6b60506e03a6ba45c3570ef46b282e15ab80f.tgz
dateCreated: '2025-12-12T22:14:57.208324Z'
digest: 6d1c1bcecd9e6d3e0c494188a7f32e21388a8f667d0482b6c74dd0e1073f0155
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
