annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-b59c71224cd69041b6d92e9a4d7a1aaddcf9eae9.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-b59c71224cd69041b6d92e9a4d7a1aaddcf9eae9.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-b59c71224cd69041b6d92e9a4d7a1aaddcf9eae9.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-b59c71224cd69041b6d92e9a4d7a1aaddcf9eae9.tgz
dateCreated: '2025-12-02T12:56:42.073807Z'
digest: abd49d0f166bccc06f671c3202f4aaedcfed29052e808f615424f8aa1e79bf01
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
