annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.0-caff260eff06695e3235b5dbf0c7726447617c36.tgz
dateCreated: '2025-12-28T08:29:02.250551Z'
digest: 99913990652ddb130cfb6b679dd2b8de9b14cc6ec94791253fc7edf9adb25392
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
