annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-f2354442d119e93d07105e52e78de8380da32404.tgz
dateCreated: '2025-12-09T10:49:56.980530Z'
digest: 148b4114017cc3731283a5a9159bbb0d796e4e004f7511e634635f7fa0b9325c
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
