annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-897dc99b624d7f3a779faa0f3cc7a7c5b5ff86be.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-897dc99b624d7f3a779faa0f3cc7a7c5b5ff86be.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-897dc99b624d7f3a779faa0f3cc7a7c5b5ff86be.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-897dc99b624d7f3a779faa0f3cc7a7c5b5ff86be.tgz
dateCreated: '2025-12-04T15:44:01.131986Z'
digest: ec85ce28b0ebf3a742a76163cdae8b7916ead499b652dfa43c590244cb4f3757
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
