annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-18.0.0-d557c4db453e21f6913e3656b2a165f1de1959ea.tgz
dateCreated: '2025-12-09T18:59:48.325926Z'
digest: 4f50c714f18f2e0aa5f778b34816563ac7b4dfae0ab967b8ee73121b4caf5e1b
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
restrictions:
  clusterSingleton: true
