annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.1-888845d03a156207b7c2b5e03b901200f440bd5c.tgz
dateCreated: '2025-12-29T14:20:55.083339Z'
digest: 5daf53015a0499dddd391f49ff29d99e2b2308537e4e7d11624ddef966504f81
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
