annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-19.0.0.tgz
dateCreated: '2025-12-16T11:41:41.002670Z'
digest: 0ce036996b9f565a98b764bf3db6ca1163c64b6939b4dc6a5d742e36e3102ea5
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
restrictions:
  clusterSingleton: true
