annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-7bb29112ace1015959cc7c2e5586a90e83fbe547.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-7bb29112ace1015959cc7c2e5586a90e83fbe547.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-7bb29112ace1015959cc7c2e5586a90e83fbe547.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-7bb29112ace1015959cc7c2e5586a90e83fbe547.tgz
dateCreated: '2025-11-03T11:39:53.993072Z'
digest: 900bdb6f3f7f417c5f86321140e963e62277a68c17edf940392b287f113adf76
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
