annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-1754bfca4b017667f0c2ca217796f45adb09ea8e.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-1754bfca4b017667f0c2ca217796f45adb09ea8e.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-1754bfca4b017667f0c2ca217796f45adb09ea8e.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-1754bfca4b017667f0c2ca217796f45adb09ea8e.tgz
dateCreated: '2025-12-02T12:57:11.716330Z'
digest: d4b8c7ddf7f5e0f344a68ee9a881769443cc4e5ee7c86f058ed1fb32eb4cfab3
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
