annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-b554d9517fca2bb5e357628689b8776592bd848f.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-b554d9517fca2bb5e357628689b8776592bd848f.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-b554d9517fca2bb5e357628689b8776592bd848f.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-b554d9517fca2bb5e357628689b8776592bd848f.tgz
dateCreated: '2025-11-08T18:30:01.135844Z'
digest: 8b43b5a027b03e417deb31317c373e45d9b4f5ee5e04e10602cb23ac2c53ded9
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
