annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.1-12dbeb96276d2987addd8817e49859232c9563d3.tgz
dateCreated: '2026-01-14T05:09:48.871227Z'
digest: 65a0ed4e2985295abeef7ccac2f28f5bab46e1e7c63c94d31b909af64bb605d9
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
