annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-e530cf0953388e44ce2c516597764e9db4c51d33.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-e530cf0953388e44ce2c516597764e9db4c51d33.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-e530cf0953388e44ce2c516597764e9db4c51d33.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-e530cf0953388e44ce2c516597764e9db4c51d33.tgz
dateCreated: '2025-11-04T12:13:04.924232Z'
digest: 44aafc4f131b34fdc52541ba1e236291aa6c992ee3e39e8fc3269de23c597a97
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
