annotations:
  application.giantswarm.io/team: phoenix
chartApiVersion: v2
chartFile: prometheus-blackbox-exporter-0.5.0-72a278f8086ab022dc1125afa65d0255d08d7a65.tgz
dateCreated: '2026-01-28T09:37:32.556736Z'
digest: a279417aff8a0203d93f8dc3d63aa9435791f9a43d6d4011fbc05607e7049020
home: https://github.com/giantswarm/prometheus-blackbox-exporter-app
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
