annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-f1947c07794deb2f0b0c2572f662f7299a105ef6.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-f1947c07794deb2f0b0c2572f662f7299a105ef6.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-f1947c07794deb2f0b0c2572f662f7299a105ef6.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-f1947c07794deb2f0b0c2572f662f7299a105ef6.tgz
dateCreated: '2025-12-04T15:44:19.254835Z'
digest: d9a6cb696922ef0dabc8cc8e940ce2b6840275c25f3bea185b8c70b7edeeca4e
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
