annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-26e74d80009c29f0ac98909ad294ee4533122572.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-26e74d80009c29f0ac98909ad294ee4533122572.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-26e74d80009c29f0ac98909ad294ee4533122572.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-26e74d80009c29f0ac98909ad294ee4533122572.tgz
dateCreated: '2025-12-05T17:39:47.370301Z'
digest: 443434f5d416dd340037e9e907fb9939d3d12c8035375de4cda83bf0e9ed4972
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
