annotations:
  application.giantswarm.io/team: phoenix
chartApiVersion: v2
chartFile: prometheus-blackbox-exporter-0.5.0-14419ed8524a4aadcc09d3c0d883549cb10472cc.tgz
dateCreated: '2026-01-05T16:07:33.719743Z'
digest: 782c8b324dbf3aa5b18316f89938e6c4fbbab3ea076f58a44b0c81da5c96f5da
home: https://github.com/giantswarm/prometheus-blackbox-exporter-app
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
