annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-ee57b9c960a4c3c150a8d39bc2427f1cef710d5d.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-ee57b9c960a4c3c150a8d39bc2427f1cef710d5d.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-ee57b9c960a4c3c150a8d39bc2427f1cef710d5d.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-ee57b9c960a4c3c150a8d39bc2427f1cef710d5d.tgz
dateCreated: '2025-12-04T12:44:40.451844Z'
digest: cf66b8ee450f2b729b296ad223c28079b6acaf0186df4c16161c66b4373b7a68
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
