annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-1ebfa4e720d4cbbdb0f9c25b477f811719d2a198.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-1ebfa4e720d4cbbdb0f9c25b477f811719d2a198.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-1ebfa4e720d4cbbdb0f9c25b477f811719d2a198.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-1ebfa4e720d4cbbdb0f9c25b477f811719d2a198.tgz
dateCreated: '2025-11-04T11:37:23.403004Z'
digest: 9da11e6549721075b152dc85fc8625506537371933d2e104ad3514922b13a8af
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
