annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-b4154e2a2604d07355c902763259b35823f0b278.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-b4154e2a2604d07355c902763259b35823f0b278.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-b4154e2a2604d07355c902763259b35823f0b278.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-b4154e2a2604d07355c902763259b35823f0b278.tgz
dateCreated: '2025-12-02T12:55:52.587761Z'
digest: 9a736df20034502471678f670b0d66803f45f4d52bba16a12158e11fc5bee9e3
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
