annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.1-760cc714a44dc13be117c93e915a7528c7e0f0b8.tgz
dateCreated: '2026-01-07T00:46:55.813942Z'
digest: 86b152401a4129761d8c48b4b7a73d53f1146a41e17afa745795ef125a64eed4
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
