annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.0-ece0998f099807d19b97cdc7b0a57416b83100aa.tgz
dateCreated: '2025-12-28T19:39:04.447031Z'
digest: eecfa590c4854b4449fdb2238055f109ad30b24abc5b63941fb1c6c8f7bffa60
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
