annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-8d74f0e4df2376d1d76dfe37b4cfa93c664325ab.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-8d74f0e4df2376d1d76dfe37b4cfa93c664325ab.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-8d74f0e4df2376d1d76dfe37b4cfa93c664325ab.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-8d74f0e4df2376d1d76dfe37b4cfa93c664325ab.tgz
dateCreated: '2025-11-25T21:40:28.564947Z'
digest: 12c9c227bd941fd19d4f645c2dc482d5f45f27b511c931057c6df12a67675f3b
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
