annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-18.0.0-3fb64f9fef459304d220dd95e94f9a030220c1d5.tgz
dateCreated: '2025-12-16T11:38:29.689886Z'
digest: 912a7192cab8b604a65da3692d373fb39262de609aedd3f350803509f8bc42eb
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
restrictions:
  clusterSingleton: true
