annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-18.0.0-d4bfc8fc12e4b1184ecbdf11962372de38e7245a.tgz
dateCreated: '2025-12-11T13:57:21.046882Z'
digest: af9021e306693bf74f58e4140b8072e59955bd657926bfa7dc9a2194dbb4a0e2
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
restrictions:
  clusterSingleton: true
