annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/prometheus-operator-crd-18.0.0-d3a9c496e61c605dfb524903f3c39a81ba939206.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/prometheus-operator-crd-18.0.0-d3a9c496e61c605dfb524903f3c39a81ba939206.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/prometheus-operator-crd-18.0.0-d3a9c496e61c605dfb524903f3c39a81ba939206.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-operator-crd-18.0.0-d3a9c496e61c605dfb524903f3c39a81ba939206.tgz
dateCreated: '2025-11-20T16:35:22.630247Z'
digest: d49895a759a993467bfeaa151d585137cd7d417990a7a92de2d5d92c38b192ba
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
restrictions:
  clusterSingleton: true
