annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-7ef04b974438bc8ffda2bdaaf7f6c741be7787a3.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-7ef04b974438bc8ffda2bdaaf7f6c741be7787a3.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-7ef04b974438bc8ffda2bdaaf7f6c741be7787a3.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-7ef04b974438bc8ffda2bdaaf7f6c741be7787a3.tgz
dateCreated: '2025-11-07T16:36:54.987140Z'
digest: 9df706df5c22d373ce16bc38fda24d339afe478c929194a8fd52ce763e144b3c
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
