annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.0-97c039bdd1bf3eaf06aef32c7a974bdd87337eee.tgz
dateCreated: '2025-12-28T18:50:50.026382Z'
digest: ff4175b3feace225b11cfbb0f90b3aeb0906fd27e1ce69c2ab13ccd3d76754b0
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
