annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-f302ecad5991733f13fe7182abdb1ecb19c61d46.tgz
dateCreated: '2025-12-16T11:24:12.513416Z'
digest: d98103ce1aeb88a79ce667b35ba2eeab5bd7e85c620bae1da058e165424ca1dc
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
