annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-24f3cdcfdc16adbaf0af7565ddc586a187e14535.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-24f3cdcfdc16adbaf0af7565ddc586a187e14535.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-24f3cdcfdc16adbaf0af7565ddc586a187e14535.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-24f3cdcfdc16adbaf0af7565ddc586a187e14535.tgz
dateCreated: '2025-11-11T17:42:14.883779Z'
digest: a365fb2d826815ad93e6f8afc004b1d983056fef5e152cb6e6409066ab2f7d20
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
