annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-e7fbd9c64836f60ebb30ec63283fc0145a677fd5.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-e7fbd9c64836f60ebb30ec63283fc0145a677fd5.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-e7fbd9c64836f60ebb30ec63283fc0145a677fd5.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-e7fbd9c64836f60ebb30ec63283fc0145a677fd5.tgz
dateCreated: '2025-11-21T16:33:02.828743Z'
digest: 4e0108979fbeef2b0a4d983a84226bcb50e4b0e40691d093f9348145166733c0
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
