annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-d2dfd2788d35c9f360e985dc5bd32c036b9efe8c.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-d2dfd2788d35c9f360e985dc5bd32c036b9efe8c.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-test-catalog/kube-prometheus-stack-18.1.0-d2dfd2788d35c9f360e985dc5bd32c036b9efe8c.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-d2dfd2788d35c9f360e985dc5bd32c036b9efe8c.tgz
dateCreated: '2025-11-21T15:38:50.510485Z'
digest: 16648a3da785cbc25a574d1e4a382ca6a65ad406e8a1f7d5fddbd2f29d89d475
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
