annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-7e6a91987339fc83e5a5bedc9de415e9ff2b343c.tgz
dateCreated: '2025-12-16T11:51:55.247031Z'
digest: d9c550fb8f3c64915fbd26620cf2534c9898dabfb73ea47d8385e6db1f964589
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
